/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSystemIndexRouteImport } from './routes/_app/system/index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/_app/submissions/index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppDistributionsIndexRouteImport } from './routes/_app/distributions/index'
import { Route as AppReportsRecentActivtiesIndexRouteImport } from './routes/_app/reports/recent-activties/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemIndexRoute = AppSystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionsIndexRoute = AppDistributionsIndexRouteImport.update({
  id: '/distributions/',
  path: '/distributions/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRecentActivtiesIndexRoute =
  AppReportsRecentActivtiesIndexRouteImport.update({
    id: '/reports/recent-activties/',
    path: '/reports/recent-activties/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/distributions': typeof AppDistributionsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/submissions': typeof AppSubmissionsIndexRoute
  '/system': typeof AppSystemIndexRoute
  '/reports/recent-activties': typeof AppReportsRecentActivtiesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/distributions': typeof AppDistributionsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/submissions': typeof AppSubmissionsIndexRoute
  '/system': typeof AppSystemIndexRoute
  '/reports/recent-activties': typeof AppReportsRecentActivtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/distributions/': typeof AppDistributionsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/submissions/': typeof AppSubmissionsIndexRoute
  '/_app/system/': typeof AppSystemIndexRoute
  '/_app/reports/recent-activties/': typeof AppReportsRecentActivtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/distributions'
    | '/reports'
    | '/settings'
    | '/students'
    | '/submissions'
    | '/system'
    | '/reports/recent-activties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/distributions'
    | '/reports'
    | '/settings'
    | '/students'
    | '/submissions'
    | '/system'
    | '/reports/recent-activties'
  id:
    | '__root__'
    | '/_app'
    | '/_auth/login'
    | '/_app/'
    | '/_app/distributions/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/students/'
    | '/_app/submissions/'
    | '/_app/system/'
    | '/_app/reports/recent-activties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system/': {
      id: '/_app/system/'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submissions/': {
      id: '/_app/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distributions/': {
      id: '/_app/distributions/'
      path: '/distributions'
      fullPath: '/distributions'
      preLoaderRoute: typeof AppDistributionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/recent-activties/': {
      id: '/_app/reports/recent-activties/'
      path: '/reports/recent-activties'
      fullPath: '/reports/recent-activties'
      preLoaderRoute: typeof AppReportsRecentActivtiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDistributionsIndexRoute: typeof AppDistributionsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
  AppSystemIndexRoute: typeof AppSystemIndexRoute
  AppReportsRecentActivtiesIndexRoute: typeof AppReportsRecentActivtiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDistributionsIndexRoute: AppDistributionsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
  AppSystemIndexRoute: AppSystemIndexRoute,
  AppReportsRecentActivtiesIndexRoute: AppReportsRecentActivtiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
